baseURL = 'https://example.org/'
languageCode = 'zh-CN'
title = 'yanzhe-Xiao'
theme = 'hugo-theme-reimu'

defaultContentLanguage = 'zh-CN'
defaultContentLanguageInSubdir = false

[languages]
[languages.zh-CN]
languageName = '简体中文'
weight = 1
hasCJKLanguage = true

[markup.goldmark.extensions.passthrough]
enable = true
delimiters.block = [["\\[", "\\]"], ["$$", "$$"]]
delimiters.inline = [["\\(", "\\)"], ["$", "$"]]

[markup.highlight]
guessSyntax = true
noClasses = false

[outputs]
home = ["Algolia", "HTML", "RSS"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true
